// <auto-generated />
using EducationPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EducationPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512185719_role")]
    partial class role
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EducationPlatform.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("ImgPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "Alice@gmail.com",
                            Grade = 90,
                            Name = "Alice",
                            Password = "$2a$11$kBVqJIocpmmTXx2zdtn9IO4dCPc3Uv6x7IAiLJ9xdijTmktSQvWKu",
                            Role = "student"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Email = "BobBob@gmail.com",
                            Grade = 85,
                            Name = "Bob",
                            Password = "$2a$11$b25j/M9MfEP5FJaXDHOxGOUJOc84qhadMWzw75m4rN7o9hZu1fEpC",
                            Role = "student"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Email = "Charlie@gmail.com",
                            Grade = 92,
                            Name = "Charlie",
                            Password = "$2a$11$PpUhzo3uokrgzEQDdceQTe.VZXR8WvrVQdjvaxccchZMps4KhzbVa",
                            Role = "student"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
